export const FETCH_ALL_PRODUCT_REQUEST = "FETCH_ALL_PRODUCT_REQUEST";
export const FETCH_ALL_PRODUCT_SUCCESS = "FETCH_ALL_PRODUCT_SUCCESS";
export const FETCH_ALL_PRODUCT_FAILURE = "FETCH_ALL_PRODUCT_FAILURE";

export const FETCH_PRODUCT_PERPAGE_REQUEST = "FETCH_PRODUCT_PERPAGE_REQUEST";
export const FETCH_PRODUCT_PERPAGE_SUCCESS = "FETCH_PRODUCT_PERPAGE_SUCCESS";
export const FETCH_PRODUCT_PERPAGE_FAILURE = "FETCH_PRODUCT_PERPAGE_FAILURE";
export const FETCH_ALL_PRODUCT_WHEN_CHANGE_TYPE =
  "FETCH_ALL_PRODUCT_WHEN_CHANGE_TYPE";
export const FETCH_ALL_PRODUCT_WHEN_CHANGE_TYPE_SUCCESS =
  "FETCH_ALL_PRODUCT_WHEN_CHANGE_TYPE_SUCCESS";
export const FETCH_ALL_PRODUCT_WHEN_CHANGE_BRAND =
  "FETCH_ALL_PRODUCT_WHEN_CHANGE_BRAND";
export const FETCH_ALL_PRODUCT_WHEN_CHANGE_BRAND_SUCCESS =
  "FETCH_ALL_PRODUCT_WHEN_CHANGE_BRAND_SUCCESS";
export const FETCH_ALL_PRODUCT_WHEN_CHANGE_RATING =
  "FETCH_ALL_PRODUCT_WHEN_CHANGE_RATING";
export const FETCH_ALL_PRODUCT_WHEN_CHANGE_RATING_SUCCESS =
  "FETCH_ALL_PRODUCT_WHEN_CHANGE_RATING_SUCCESS";
